[meta]
name = "stripe-dot-dev"
version = "1.0.0"
generator = "crawlwe"
mode = "hybrid"
captured_at = "2026-01-31T02:00:04.381502920+00:00"

[source]
url = "https://stripe.dev"
title = "Stripe Dot Dev"

[technologies]

[assets]
svgs = 14
images = 0
fonts = 4

[assets.svgs]
icons = 11 # Small reusable icons
logos = 1 # Brand logos
illustrations = 2 # Large decorative SVGs

[assets.fonts]
"sohne-var" = { weights = ["1 10000", "400"], files = ["assets/fonts/Sohne.woff2", "assets/fonts/Sohne-BuchKursiv.woff2"] }
"sohne-mono" = { weights = ["300", "100"], files = ["assets/fonts/SohneMono-Extraleicht.woff2", "assets/fonts/SohneMono-Buch.woff2"] }

[css]
variables = 28
keyframes = 3
colors = 11

# Import paths for use in your project:
# import styles from './styles.css'
# import { icons } from './assets/svgs/icons/'
# import fonts from './assets/fonts/'
