//! ZAD Code Generator - Generates code for different target languages

use crate::zad::ast::*;
use crate::zad::{Target, Result};

pub struct CodeGenerator {
    target: Target,
}

impl CodeGenerator {
    pub fn new(target: Target) -> Self {
        Self { target }
    }

    pub fn generate(&self, program: &Program) -> Result<String> {
        let mut evaluator = crate::zad::Evaluator::new();
        let raw_output = evaluator.eval(program)?;

        // For Raw target, just return the output
        if self.target == Target::Raw {
            return Ok(raw_output);
        }

        // Otherwise, wrap in appropriate language structure
        Ok(self.wrap_output(&raw_output))
    }

    fn wrap_output(&self, content: &str) -> String {
        match self.target {
            Target::Zig => format!(
                "// Generated by ZAD\n\
                 const std = @import(\"std\");\n\n\
                 {}\n",
                content
            ),
            Target::Rust => format!(
                "// Generated by ZAD\n\n\
                 {}\n",
                content
            ),
            Target::TypeScript => format!(
                "// Generated by ZAD\n\n\
                 {}\n",
                content
            ),
            Target::Python => format!(
                "# Generated by ZAD\n\n\
                 {}\n",
                content
            ),
            Target::Raw => content.to_string(),
        }
    }
}

/// Helper for generating Zig code
pub struct ZigGen;

impl ZigGen {
    pub fn struct_field(name: &str, typ: &str) -> String {
        format!("    {}: {},", name, typ)
    }

    pub fn struct_def(name: &str, fields: &[(String, String)]) -> String {
        let field_lines: Vec<String> = fields
            .iter()
            .map(|(n, t)| Self::struct_field(n, t))
            .collect();

        format!(
            "pub const {} = struct {{\n{}\n}};",
            name,
            field_lines.join("\n")
        )
    }

    pub fn function_def(
        vis: &str,
        name: &str,
        params: &[(String, String)],
        return_type: &str,
        body: &str,
    ) -> String {
        let params_str: Vec<String> = params
            .iter()
            .map(|(n, t)| format!("{}: {}", n, t))
            .collect();

        format!(
            "{} fn {}({}) {} {{\n{}\n}}",
            vis,
            name,
            params_str.join(", "),
            return_type,
            body
        )
    }

    pub fn const_def(name: &str, typ: &str, value: &str) -> String {
        format!("const {}: {} = {};", name, typ, value)
    }

    pub fn var_def(name: &str, typ: &str, value: &str) -> String {
        format!("var {}: {} = {};", name, typ, value)
    }

    pub fn if_stmt(condition: &str, then_body: &str, else_body: Option<&str>) -> String {
        match else_body {
            Some(e) => format!("if ({}) {{\n{}\n}} else {{\n{}\n}}", condition, then_body, e),
            None => format!("if ({}) {{\n{}\n}}", condition, then_body),
        }
    }

    pub fn for_loop(iterable: &str, binding: &str, body: &str) -> String {
        format!("for ({}) |{}| {{\n{}\n}}", iterable, binding, body)
    }

    pub fn switch_stmt(value: &str, cases: &[(String, String)], default: Option<&str>) -> String {
        let case_lines: Vec<String> = cases
            .iter()
            .map(|(pattern, body)| format!("    {} => {{\n{}\n    }},", pattern, body))
            .collect();

        let default_line = default
            .map(|d| format!("    else => {{\n{}\n    }},", d))
            .unwrap_or_default();

        format!(
            "switch ({}) {{\n{}\n{}\n}}",
            value,
            case_lines.join("\n"),
            default_line
        )
    }
}

/// Helper for generating Rust code
pub struct RustGen;

impl RustGen {
    pub fn struct_field(name: &str, typ: &str) -> String {
        format!("    pub {}: {},", name, typ)
    }

    pub fn struct_def(name: &str, fields: &[(String, String)], derives: &[&str]) -> String {
        let derives_str = if derives.is_empty() {
            String::new()
        } else {
            format!("#[derive({})]\n", derives.join(", "))
        };

        let field_lines: Vec<String> = fields
            .iter()
            .map(|(n, t)| Self::struct_field(n, t))
            .collect();

        format!(
            "{}pub struct {} {{\n{}\n}}",
            derives_str,
            name,
            field_lines.join("\n")
        )
    }

    pub fn enum_def(name: &str, variants: &[(String, Option<String>)], derives: &[&str]) -> String {
        let derives_str = if derives.is_empty() {
            String::new()
        } else {
            format!("#[derive({})]\n", derives.join(", "))
        };

        let variant_lines: Vec<String> = variants
            .iter()
            .map(|(n, t)| match t {
                Some(typ) => format!("    {}({}),", n, typ),
                None => format!("    {},", n),
            })
            .collect();

        format!(
            "{}pub enum {} {{\n{}\n}}",
            derives_str,
            name,
            variant_lines.join("\n")
        )
    }

    pub fn impl_block(name: &str, methods: &[String]) -> String {
        format!(
            "impl {} {{\n{}\n}}",
            name,
            methods.join("\n\n")
        )
    }

    pub fn function_def(
        vis: &str,
        name: &str,
        params: &[(String, String)],
        return_type: Option<&str>,
        body: &str,
    ) -> String {
        let params_str: Vec<String> = params
            .iter()
            .map(|(n, t)| format!("{}: {}", n, t))
            .collect();

        let return_str = return_type
            .map(|t| format!(" -> {}", t))
            .unwrap_or_default();

        format!(
            "{}fn {}({}){} {{\n{}\n}}",
            if vis.is_empty() { "" } else { "pub " },
            name,
            params_str.join(", "),
            return_str,
            body
        )
    }
}

/// Helper for generating TypeScript code
pub struct TsGen;

impl TsGen {
    pub fn interface_def(name: &str, fields: &[(String, String, bool)]) -> String {
        let field_lines: Vec<String> = fields
            .iter()
            .map(|(n, t, optional)| {
                if *optional {
                    format!("  {}?: {};", n, t)
                } else {
                    format!("  {}: {};", n, t)
                }
            })
            .collect();

        format!(
            "interface {} {{\n{}\n}}",
            name,
            field_lines.join("\n")
        )
    }

    pub fn type_def(name: &str, definition: &str) -> String {
        format!("type {} = {};", name, definition)
    }

    pub fn function_def(
        name: &str,
        params: &[(String, String)],
        return_type: &str,
        body: &str,
        is_async: bool,
    ) -> String {
        let params_str: Vec<String> = params
            .iter()
            .map(|(n, t)| format!("{}: {}", n, t))
            .collect();

        let async_str = if is_async { "async " } else { "" };

        format!(
            "{}function {}({}): {} {{\n{}\n}}",
            async_str,
            name,
            params_str.join(", "),
            return_type,
            body
        )
    }

    pub fn arrow_function(
        params: &[(String, String)],
        return_type: &str,
        body: &str,
    ) -> String {
        let params_str: Vec<String> = params
            .iter()
            .map(|(n, t)| format!("{}: {}", n, t))
            .collect();

        format!(
            "({}): {} => {{\n{}\n}}",
            params_str.join(", "),
            return_type,
            body
        )
    }

    pub fn class_def(
        name: &str,
        properties: &[(String, String, String)],  // (name, type, visibility)
        methods: &[String],
    ) -> String {
        let prop_lines: Vec<String> = properties
            .iter()
            .map(|(n, t, v)| format!("  {} {}: {};", v, n, t))
            .collect();

        format!(
            "class {} {{\n{}\n\n{}\n}}",
            name,
            prop_lines.join("\n"),
            methods.join("\n\n")
        )
    }
}
