//! Export command - Generate project.toml for captured content

use std::fs;
use std::path::Path;

use crawlwe_core::pipeline::{
    CssMicroparser, LibMicroparser, HtmlMicroparser,
    DetectedLibrary, LibrarySource, CssParseResult,
};
use crawlwe_core::export::LibraryCDN;

pub fn run(path: &Path, force: bool) -> Result<(), Box<dyn std::error::Error>> {
    println!("CrawlWe Export");
    println!("==============");
    println!("Path: {:?}", path);

    let project_toml_path = path.join("project.toml");
    if project_toml_path.exists() && !force {
        println!("\nproject.toml already exists. Use --force to overwrite.");
        return Ok(());
    }

    // Read captured content
    let html = fs::read_to_string(path.join("index.html"))
        .or_else(|_| fs::read_to_string(path.join("data/raw.html")))
        .unwrap_or_default();
    let css = fs::read_to_string(path.join("styles.css")).unwrap_or_default();

    // Read metadata if available
    let metadata: serde_json::Value = fs::read_to_string(path.join("data/metadata.json"))
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or(serde_json::json!({}));

    let url = metadata["url"].as_str().unwrap_or("https://example.com");
    let title = metadata["title"].as_str().unwrap_or("Captured Page");

    // Parse content
    let html_parsed = HtmlMicroparser::parse(&html);
    let css_parsed = CssMicroparser::parse(&css);

    // Get script URLs
    let script_urls: Vec<String> = html_parsed.scripts
        .iter()
        .filter_map(|s| s.src.clone())
        .collect();

    // Detect libraries
    let js_inline = ""; // Would need to read from scripts/ directory
    let lib_result = LibMicroparser::parse(&script_urls, js_inline);

    // Generate project.toml
    let toml = generate_project_toml(url, title, &lib_result.libraries, &css_parsed);

    // Save
    fs::write(&project_toml_path, &toml)?;
    println!("\nGenerated: {:?}", project_toml_path);

    // Print summary
    println!("\nSummary:");
    println!("  URL: {}", url);
    println!("  Title: {}", title);
    println!("  Libraries: {}", lib_result.libraries.len());
    println!("  Fonts: {}", css_parsed.fonts.len());
    println!("  CSS Variables: {}", css_parsed.variables.len());

    Ok(())
}

fn generate_project_toml(
    url: &str,
    title: &str,
    libs: &[DetectedLibrary],
    css: &CssParseResult,
) -> String {

    let mut toml = String::new();

    // Meta
    toml.push_str("# Generated by CrawlWe\n\n");
    toml.push_str("[meta]\n");
    toml.push_str(&format!("name = \"{}\"\n", sanitize_name(title)));
    toml.push_str("version = \"1.0.0\"\n");
    toml.push_str("generator = \"crawlwe\"\n");
    toml.push_str(&format!("generated_at = \"{}\"\n", chrono::Utc::now().to_rfc3339()));
    toml.push('\n');

    // Source
    toml.push_str("[source]\n");
    toml.push_str(&format!("url = \"{}\"\n", url));
    toml.push_str(&format!("title = \"{}\"\n", title.replace('"', "\\\"")));
    toml.push('\n');

    // Technologies
    toml.push_str("[technologies]\n");

    let by_category: std::collections::HashMap<String, Vec<&crawlwe_core::pipeline::DetectedLibrary>> =
        libs.iter().fold(std::collections::HashMap::new(), |mut acc: std::collections::HashMap<String, Vec<&crawlwe_core::pipeline::DetectedLibrary>>, lib| {
            acc.entry(lib.category.clone()).or_default().push(lib);
            acc
        });

    if let Some(css_libs) = by_category.get("css") {
        toml.push_str(&format!("css_framework = \"{}\"\n", css_libs[0].name));
    }
    if let Some(ui_libs) = by_category.get("ui") {
        toml.push_str(&format!("ui_framework = \"{}\"\n", ui_libs[0].name));
    }

    for (category, libs) in &by_category {
        if category != "css" && category != "ui" && !libs.is_empty() {
            let names: Vec<_> = libs.iter().map(|l| format!("\"{}\"", l.name)).collect();
            toml.push_str(&format!("{}_libs = [{}]\n", category, names.join(", ")));
        }
    }
    toml.push('\n');

    // CSS Analysis
    if !css.variables.is_empty() || !css.keyframes.is_empty() {
        toml.push_str("[css_analysis]\n");
        toml.push_str(&format!("variables_count = {}\n", css.variables.len()));
        toml.push_str(&format!("keyframes_count = {}\n", css.keyframes.len()));
        toml.push_str(&format!("colors_count = {}\n", css.colors.len()));
        toml.push_str(&format!("has_media_queries = {}\n", css.stats.has_media_queries));
        toml.push('\n');
    }

    // Dependencies
    toml.push_str("[dependencies]\n\n");

    if !libs.is_empty() {
        toml.push_str("[dependencies.scripts]\n");
        for lib in libs {
            let cdn_url = match &lib.source {
                LibrarySource::Url(url) => Some(url.clone()),
                _ => LibraryCDN::get_js(&lib.name, lib.version.as_deref()),
            };
            if let Some(url) = cdn_url {
                let key = lib.name.replace('-', "_").replace('.', "_");
                if let Some(version) = &lib.version {
                    toml.push_str(&format!("{} = {{ version = \"{}\", cdn = \"{}\" }}\n", key, version, url));
                } else {
                    toml.push_str(&format!("{} = \"{}\"\n", key, url));
                }
            }
        }
        toml.push('\n');
    }

    // Fonts
    if !css.fonts.is_empty() {
        toml.push_str("[dependencies.fonts]\n");
        for font in &css.fonts {
            let url = LibraryCDN::get_font_url(font, &["400".to_string(), "700".to_string()]);
            toml.push_str(&format!("\"{}\" = {{ weights = [\"400\", \"700\"], source = \"google\", url = \"{}\" }}\n", font, url));
        }
        toml.push('\n');
    }

    // Export options
    toml.push_str("[export]\n");
    toml.push_str("minify_html = false\n");
    toml.push_str("minify_css = false\n");
    toml.push_str("inline_critical_css = false\n");

    toml
}

fn sanitize_name(name: &str) -> String {
    name.to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '-' })
        .collect::<String>()
        .trim_matches('-')
        .to_string()
}
