//! Smart CSS Extractor
//!
//! Intelligent CSS extraction that learns from actual CSS files and JS bundles.
//! No hardcoded values - everything is derived from the source.
//!
//! Strategy:
//! 1. Parse actual CSS to build class -> rule mappings
//! 2. Detect CSS patterns in compiled JS bundles
//! 3. Match HTML classes to their CSS definitions
//! 4. Generate clean, semantic CSS output

use regex::Regex;
use std::collections::{HashMap, HashSet};

/// Result of smart CSS extraction
#[derive(Debug, Clone, Default)]
pub struct SmartCssResult {
    /// Class to CSS rule mappings
    pub class_rules: HashMap<String, CssRule>,
    /// CSS variables found
    pub variables: HashMap<String, String>,
    /// Keyframe animations
    pub keyframes: HashMap<String, String>,
    /// Media queries with their rules
    pub media_queries: HashMap<String, Vec<CssRule>>,
    /// Font faces
    pub font_faces: Vec<String>,
    /// Generated clean CSS
    pub clean_css: String,
    /// Semantic class mapping (hash -> semantic)
    pub semantic_map: HashMap<String, String>,
    /// Statistics
    pub stats: SmartCssStats,
}

#[derive(Debug, Clone, Default)]
pub struct SmartCssStats {
    pub classes_found: usize,
    pub classes_mapped: usize,
    pub variables_found: usize,
    pub keyframes_found: usize,
    pub media_queries_found: usize,
    pub rules_from_css: usize,
    pub rules_from_js: usize,
}

#[derive(Debug, Clone)]
pub struct CssRule {
    pub selector: String,
    pub properties: Vec<CssProperty>,
    pub source: CssSource,
    pub specificity: u32,
}

#[derive(Debug, Clone)]
pub struct CssProperty {
    pub name: String,
    pub value: String,
    pub important: bool,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CssSource {
    Stylesheet,    // From .css file
    InlineStyle,   // From <style> tag
    CompiledJs,    // From JS bundle
    Generated,     // Generated by converter
}

/// Smart CSS Extractor
pub struct SmartCssExtractor {
    // Patterns for CSS parsing
    rule_pattern: Regex,
    property_pattern: Regex,
    variable_pattern: Regex,
    keyframe_pattern: Regex,
    media_pattern: Regex,
    font_face_pattern: Regex,

    // Patterns for JS CSS extraction
    js_css_string_pattern: Regex,
    js_style_object_pattern: Regex,
    js_template_css_pattern: Regex,
    js_module_pattern: Regex,

    // Patterns for class name analysis
    css_module_pattern: Regex,
    bem_pattern: Regex,
    tailwind_pattern: Regex,
}

impl SmartCssExtractor {
    pub fn new() -> Self {
        Self {
            // CSS rule: .class { ... } or element { ... }
            rule_pattern: Regex::new(
                r"([.#]?[\w\-\[\]=:>,\s\*\(\)]+)\s*\{([^}]+)\}"
            ).unwrap(),

            // CSS property: name: value;
            property_pattern: Regex::new(
                r"([\w-]+)\s*:\s*([^;]+?)(?:\s*(!important))?\s*;"
            ).unwrap(),

            // CSS variable: --name: value;
            variable_pattern: Regex::new(
                r"--([\w-]+)\s*:\s*([^;]+)\s*;"
            ).unwrap(),

            // @keyframes name { ... }
            keyframe_pattern: Regex::new(
                r"@keyframes\s+([\w-]+)\s*\{([\s\S]*?)\}\s*\}"
            ).unwrap(),

            // @media query { ... }
            media_pattern: Regex::new(
                r"@media\s*([^{]+)\{([\s\S]*?)\}\s*\}"
            ).unwrap(),

            // @font-face { ... }
            font_face_pattern: Regex::new(
                r"@font-face\s*\{([^}]+)\}"
            ).unwrap(),

            // JS CSS string patterns (multiple strategies)
            js_css_string_pattern: Regex::new(
                r#"["']([.#][\w\-\[\]:>,\s]+\s*\{[^}]+\})["']"#
            ).unwrap(),

            // JS style object: { backgroundColor: 'red', fontSize: '16px' }
            js_style_object_pattern: Regex::new(
                r"\{\s*((?:[\w]+\s*:\s*[^,}]+,?\s*)+)\}"
            ).unwrap(),

            // Template literal CSS: `css content`
            js_template_css_pattern: Regex::new(
                r"`([^`]*\{[^`]*:[^`]*;[^`]*\}[^`]*)`"
            ).unwrap(),

            // CSS module pattern in compiled JS
            js_module_pattern: Regex::new(
                r#"exports\s*=\s*\{([^}]+)\}|module\.exports\s*=\s*\{([^}]+)\}"#
            ).unwrap(),

            // CSS Module: ComponentName_className__hash
            css_module_pattern: Regex::new(
                r"([A-Z][a-zA-Z0-9]*)_([a-zA-Z][a-zA-Z0-9_]*)__([a-zA-Z0-9_]{4,})"
            ).unwrap(),

            // BEM: block__element--modifier
            bem_pattern: Regex::new(
                r"([a-z][a-z0-9]*)(?:__([a-z][a-z0-9]*))?(?:--([a-z][a-z0-9]*))?"
            ).unwrap(),

            // Tailwind-like: prefix-value or compound-class
            tailwind_pattern: Regex::new(
                r"^([a-z]+)(?:-([a-z0-9\[\]/.]+))?$"
            ).unwrap(),
        }
    }

    /// Extract CSS rules from CSS content
    pub fn extract_from_css(&self, css: &str) -> SmartCssResult {
        let mut result = SmartCssResult::default();

        // Extract CSS variables first (they're often at :root)
        self.extract_variables(css, &mut result);

        // Extract keyframes
        self.extract_keyframes(css, &mut result);

        // Extract font-faces
        self.extract_font_faces(css, &mut result);

        // Extract media queries and their contents
        self.extract_media_queries(css, &mut result);

        // Extract regular rules
        self.extract_rules(css, &mut result, CssSource::Stylesheet);

        result
    }

    /// Extract CSS patterns from compiled JavaScript
    pub fn extract_from_js(&self, js_code: &str) -> SmartCssResult {
        let mut result = SmartCssResult::default();

        // Strategy 1: Look for CSS strings in the JS
        for cap in self.js_css_string_pattern.captures_iter(js_code) {
            let css_content = &cap[1];
            self.extract_rules(css_content, &mut result, CssSource::CompiledJs);
        }

        // Strategy 2: Look for template literal CSS
        for cap in self.js_template_css_pattern.captures_iter(js_code) {
            let css_content = &cap[1];
            if self.looks_like_css(css_content) {
                self.extract_rules(css_content, &mut result, CssSource::CompiledJs);
            }
        }

        // Strategy 3: Extract style objects and convert to CSS
        self.extract_style_objects(js_code, &mut result);

        // Strategy 4: Find CSS-in-JS patterns
        self.extract_css_in_js(js_code, &mut result);

        result
    }

    /// Learn class mappings from HTML and CSS
    pub fn learn_mappings(&self, html: &str, css: &str) -> SmartCssResult {
        let mut result = self.extract_from_css(css);

        // Extract all class names from HTML
        let html_classes = self.extract_html_classes(html);

        // For each HTML class, try to find its CSS rule
        for class in &html_classes {
            result.stats.classes_found += 1;

            // Check if we have a rule for this class
            if result.class_rules.contains_key(class) {
                result.stats.classes_mapped += 1;
                continue;
            }

            // Try to find a matching rule (case insensitive, partial match)
            let selector = format!(".{}", class);
            for (existing_selector, rule) in &result.class_rules {
                if existing_selector.to_lowercase().contains(&class.to_lowercase()) {
                    // Found a match - create semantic mapping
                    if let Some(semantic) = self.generate_semantic_name(class) {
                        result.semantic_map.insert(class.clone(), semantic);
                    }
                    result.stats.classes_mapped += 1;
                    break;
                }
            }
        }

        result
    }

    /// Merge multiple CSS extraction results
    pub fn merge(&self, results: Vec<SmartCssResult>) -> SmartCssResult {
        let mut merged = SmartCssResult::default();

        for result in results {
            // Merge class rules (later wins on conflict)
            for (selector, rule) in result.class_rules {
                merged.class_rules.insert(selector, rule);
            }

            // Merge variables
            for (name, value) in result.variables {
                merged.variables.insert(name, value);
            }

            // Merge keyframes
            for (name, content) in result.keyframes {
                merged.keyframes.insert(name, content);
            }

            // Merge font-faces
            merged.font_faces.extend(result.font_faces);

            // Merge semantic map
            for (original, semantic) in result.semantic_map {
                merged.semantic_map.insert(original, semantic);
            }

            // Accumulate stats
            merged.stats.classes_found += result.stats.classes_found;
            merged.stats.classes_mapped += result.stats.classes_mapped;
            merged.stats.variables_found += result.stats.variables_found;
            merged.stats.keyframes_found += result.stats.keyframes_found;
            merged.stats.rules_from_css += result.stats.rules_from_css;
            merged.stats.rules_from_js += result.stats.rules_from_js;
        }

        // Generate clean CSS
        merged.clean_css = self.generate_clean_css(&merged);

        merged
    }

    /// Generate clean, formatted CSS output
    pub fn generate_clean_css(&self, result: &SmartCssResult) -> String {
        let mut css = String::new();

        // CSS Variables
        if !result.variables.is_empty() {
            css.push_str(":root {\n");
            for (name, value) in &result.variables {
                css.push_str(&format!("  --{}: {};\n", name, value));
            }
            css.push_str("}\n\n");
        }

        // Font faces
        for font_face in &result.font_faces {
            css.push_str(&format!("@font-face {{\n{}\n}}\n\n", font_face));
        }

        // Keyframes
        for (name, content) in &result.keyframes {
            css.push_str(&format!("@keyframes {} {{\n{}\n}}\n\n", name, content));
        }

        // Regular rules (sorted by selector for consistency)
        let mut selectors: Vec<_> = result.class_rules.keys().collect();
        selectors.sort();

        for selector in selectors {
            if let Some(rule) = result.class_rules.get(selector) {
                css.push_str(&self.format_rule(rule));
                css.push_str("\n\n");
            }
        }

        // Media queries
        for (query, rules) in &result.media_queries {
            css.push_str(&format!("@media {} {{\n", query));
            for rule in rules {
                css.push_str("  ");
                css.push_str(&self.format_rule(rule).replace('\n', "\n  "));
                css.push_str("\n");
            }
            css.push_str("}\n\n");
        }

        css
    }

    /// Replace hashed class names with semantic ones in HTML
    pub fn semanticize_html(&self, html: &str, semantic_map: &HashMap<String, String>) -> String {
        let mut result = html.to_string();

        // Sort by length (longest first) to avoid partial replacements
        let mut mappings: Vec<_> = semantic_map.iter().collect();
        mappings.sort_by(|a, b| b.0.len().cmp(&a.0.len()));

        for (original, semantic) in mappings {
            result = result.replace(original, semantic);
        }

        result
    }

    // === Private helper methods ===

    fn extract_variables(&self, css: &str, result: &mut SmartCssResult) {
        for cap in self.variable_pattern.captures_iter(css) {
            let name = cap[1].to_string();
            let value = cap[2].trim().to_string();
            result.variables.insert(name, value);
            result.stats.variables_found += 1;
        }
    }

    fn extract_keyframes(&self, css: &str, result: &mut SmartCssResult) {
        for cap in self.keyframe_pattern.captures_iter(css) {
            let name = cap[1].to_string();
            let content = cap[2].trim().to_string();
            result.keyframes.insert(name, content);
            result.stats.keyframes_found += 1;
        }
    }

    fn extract_font_faces(&self, css: &str, result: &mut SmartCssResult) {
        for cap in self.font_face_pattern.captures_iter(css) {
            result.font_faces.push(cap[1].trim().to_string());
        }
    }

    fn extract_media_queries(&self, css: &str, result: &mut SmartCssResult) {
        for cap in self.media_pattern.captures_iter(css) {
            let query = cap[1].trim().to_string();
            let content = &cap[2];

            let mut rules = Vec::new();
            for rule_cap in self.rule_pattern.captures_iter(content) {
                let selector = rule_cap[1].trim().to_string();
                let properties_str = &rule_cap[2];
                let properties = self.parse_properties(properties_str);

                rules.push(CssRule {
                    selector,
                    properties,
                    source: CssSource::Stylesheet,
                    specificity: 0,
                });
            }

            if !rules.is_empty() {
                result.media_queries.insert(query, rules);
                result.stats.media_queries_found += 1;
            }
        }
    }

    fn extract_rules(&self, css: &str, result: &mut SmartCssResult, source: CssSource) {
        for cap in self.rule_pattern.captures_iter(css) {
            let selector = cap[1].trim().to_string();
            let properties_str = &cap[2];

            // Skip if it's inside a media query or keyframe (handled separately)
            if selector.starts_with('@') {
                continue;
            }

            let properties = self.parse_properties(properties_str);

            if !properties.is_empty() {
                let rule = CssRule {
                    selector: selector.clone(),
                    properties,
                    source,
                    specificity: self.calculate_specificity(&selector),
                };

                result.class_rules.insert(selector, rule);

                match source {
                    CssSource::Stylesheet | CssSource::InlineStyle => {
                        result.stats.rules_from_css += 1;
                    }
                    CssSource::CompiledJs | CssSource::Generated => {
                        result.stats.rules_from_js += 1;
                    }
                }
            }
        }
    }

    fn parse_properties(&self, css: &str) -> Vec<CssProperty> {
        let mut properties = Vec::new();

        for cap in self.property_pattern.captures_iter(css) {
            let name = cap[1].trim().to_string();
            let value = cap[2].trim().to_string();
            let important = cap.get(3).is_some();

            properties.push(CssProperty {
                name,
                value,
                important,
            });
        }

        properties
    }

    fn extract_style_objects(&self, js_code: &str, result: &mut SmartCssResult) {
        // Look for style objects and convert camelCase to kebab-case
        let style_assign = Regex::new(r#"style\s*[=:]\s*\{([^}]+)\}"#).unwrap();

        for cap in style_assign.captures_iter(js_code) {
            let content = &cap[1];
            let properties = self.parse_js_style_object(content);

            if !properties.is_empty() {
                // Generate a class name based on properties
                let class_name = format!(".generated-style-{}", result.class_rules.len());

                let rule = CssRule {
                    selector: class_name.clone(),
                    properties,
                    source: CssSource::CompiledJs,
                    specificity: 10,
                };

                result.class_rules.insert(class_name, rule);
                result.stats.rules_from_js += 1;
            }
        }
    }

    fn parse_js_style_object(&self, content: &str) -> Vec<CssProperty> {
        let mut properties = Vec::new();
        let prop_pattern = Regex::new(r#"(\w+)\s*:\s*["']([^"']+)["']|(\w+)\s*:\s*([^,}]+)"#).unwrap();

        for cap in prop_pattern.captures_iter(content) {
            let name = cap.get(1).or(cap.get(3)).map(|m| m.as_str()).unwrap_or("");
            let value = cap.get(2).or(cap.get(4)).map(|m| m.as_str()).unwrap_or("");

            if !name.is_empty() && !value.is_empty() {
                // Convert camelCase to kebab-case
                let kebab_name = self.camel_to_kebab(name);
                let clean_value = value.trim().trim_matches(|c| c == '\'' || c == '"');

                properties.push(CssProperty {
                    name: kebab_name,
                    value: clean_value.to_string(),
                    important: false,
                });
            }
        }

        properties
    }

    fn extract_css_in_js(&self, js_code: &str, result: &mut SmartCssResult) {
        // styled-components: styled.div`css content`
        let styled_pattern = Regex::new(r#"styled\.\w+`([^`]+)`"#).unwrap();
        for cap in styled_pattern.captures_iter(js_code) {
            let css_content = &cap[1];
            if self.looks_like_css(css_content) {
                // Wrap in a selector
                let wrapped = format!(".styled-{} {{ {} }}", result.class_rules.len(), css_content);
                self.extract_rules(&wrapped, result, CssSource::CompiledJs);
            }
        }

        // emotion css`...`
        let css_tagged = Regex::new(r#"css`([^`]+)`"#).unwrap();
        for cap in css_tagged.captures_iter(js_code) {
            let css_content = &cap[1];
            if self.looks_like_css(css_content) {
                let wrapped = format!(".emotion-{} {{ {} }}", result.class_rules.len(), css_content);
                self.extract_rules(&wrapped, result, CssSource::CompiledJs);
            }
        }

        // keyframes`...`
        let keyframes_tagged = Regex::new(r#"keyframes`([^`]+)`"#).unwrap();
        for cap in keyframes_tagged.captures_iter(js_code) {
            let content = &cap[1];
            let name = format!("animation-{}", result.keyframes.len());
            result.keyframes.insert(name, content.to_string());
            result.stats.keyframes_found += 1;
        }
    }

    fn extract_html_classes(&self, html: &str) -> HashSet<String> {
        let mut classes = HashSet::new();
        let class_pattern = Regex::new(r#"class(?:Name)?="([^"]+)""#).unwrap();

        for cap in class_pattern.captures_iter(html) {
            for class in cap[1].split_whitespace() {
                classes.insert(class.to_string());
            }
        }

        classes
    }

    fn generate_semantic_name(&self, class: &str) -> Option<String> {
        // CSS Module pattern
        if let Some(cap) = self.css_module_pattern.captures(class) {
            let component = &cap[1];
            let class_name = &cap[2];
            return Some(format!("{}-{}",
                self.camel_to_kebab(component),
                self.camel_to_kebab(class_name)
            ));
        }

        None
    }

    fn looks_like_css(&self, content: &str) -> bool {
        // Check if content looks like CSS
        content.contains(':') &&
        (content.contains(';') || content.contains('{')) &&
        !content.contains("function") &&
        !content.contains("=>")
    }

    fn camel_to_kebab(&self, s: &str) -> String {
        let mut result = String::new();
        for (i, c) in s.chars().enumerate() {
            if c.is_uppercase() {
                if i > 0 {
                    result.push('-');
                }
                result.push(c.to_ascii_lowercase());
            } else {
                result.push(c);
            }
        }
        result
    }

    fn calculate_specificity(&self, selector: &str) -> u32 {
        let mut specificity: u32 = 0;

        // Count IDs (#)
        specificity += (selector.matches('#').count() as u32) * 100;

        // Count classes (.) and attributes ([])
        specificity += (selector.matches('.').count() as u32) * 10;
        specificity += (selector.matches('[').count() as u32) * 10;

        // Count elements (simplified)
        let parts: Vec<_> = selector.split_whitespace().collect();
        for part in parts {
            if !part.starts_with('.') && !part.starts_with('#') && !part.starts_with('[') {
                specificity += 1;
            }
        }

        specificity
    }

    fn format_rule(&self, rule: &CssRule) -> String {
        let mut css = format!("{} {{\n", rule.selector);

        for prop in &rule.properties {
            if prop.important {
                css.push_str(&format!("  {}: {} !important;\n", prop.name, prop.value));
            } else {
                css.push_str(&format!("  {}: {};\n", prop.name, prop.value));
            }
        }

        css.push('}');
        css
    }
}

impl Default for SmartCssExtractor {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_from_css() {
        let extractor = SmartCssExtractor::new();
        let css = r#"
            :root {
                --primary: #3b82f6;
                --spacing: 1rem;
            }

            .button {
                background: var(--primary);
                padding: var(--spacing);
            }

            .container {
                max-width: 1200px;
                margin: 0 auto;
            }
        "#;

        let result = extractor.extract_from_css(css);

        assert!(result.variables.contains_key("primary"));
        assert!(result.variables.contains_key("spacing"));
        assert!(result.class_rules.contains_key(".button"));
        assert!(result.class_rules.contains_key(".container"));
    }

    #[test]
    fn test_extract_keyframes() {
        let extractor = SmartCssExtractor::new();
        let css = r#"
            @keyframes fadeIn {
                from { opacity: 0; }
                to { opacity: 1; }
            }
        "#;

        let result = extractor.extract_from_css(css);
        assert!(result.keyframes.contains_key("fadeIn"));
    }

    #[test]
    fn test_semantic_name_generation() {
        let extractor = SmartCssExtractor::new();

        let semantic = extractor.generate_semantic_name("GridLayout_grid__lsHnz");
        assert_eq!(semantic, Some("grid-layout-grid".to_string()));

        let semantic = extractor.generate_semantic_name("Nav_nav__W3s5_");
        assert_eq!(semantic, Some("nav-nav".to_string()));
    }

    #[test]
    fn test_camel_to_kebab() {
        let extractor = SmartCssExtractor::new();

        assert_eq!(extractor.camel_to_kebab("backgroundColor"), "background-color");
        assert_eq!(extractor.camel_to_kebab("GridLayout"), "grid-layout");
        assert_eq!(extractor.camel_to_kebab("fontSize"), "font-size");
    }

    #[test]
    fn test_learn_mappings() {
        let extractor = SmartCssExtractor::new();

        let html = r#"<div class="GridLayout_grid__lsHnz container"></div>"#;
        let css = r#".GridLayout_grid__lsHnz { display: grid; } .container { max-width: 100%; }"#;

        let result = extractor.learn_mappings(html, css);

        assert_eq!(result.stats.classes_found, 2);
        assert!(result.class_rules.contains_key(".GridLayout_grid__lsHnz"));
        assert!(result.class_rules.contains_key(".container"));
    }
}
