[meta]
name = "stripe-dot-dev"
version = "1.0.0"
generator = "crawlwe"
mode = "static"
captured_at = "2026-01-30T16:03:06.378055422+00:00"

[source]
url = "https://stripe.dev/"
title = "Stripe Dot Dev"

[technologies]

[dependencies.scripts]

[dependencies.fonts]
"sohne-var" = { weights = ["400", "700"], url = "https://fonts.googleapis.com/css2?family=sohne-var:wght@400;700&display=swap" }
"sohne-mono" = { weights = ["400", "700"], url = "https://fonts.googleapis.com/css2?family=sohne-mono:wght@400;700&display=swap" }
"Helvetica Neue" = { weights = ["400", "700"], url = "https://fonts.googleapis.com/css2?family=Helvetica+Neue:wght@400;700&display=swap" }
"Arial" = { weights = ["400", "700"], url = "https://fonts.googleapis.com/css2?family=Arial:wght@400;700&display=swap" }
"var(--font-dotgothic)" = { weights = ["400", "700"], url = "https://fonts.googleapis.com/css2?family=var(--font-dotgothic):wght@400;700&display=swap" }
"Courier New" = { weights = ["400", "700"], url = "https://fonts.googleapis.com/css2?family=Courier+New:wght@400;700&display=swap" }
"Courier" = { weights = ["400", "700"], url = "https://fonts.googleapis.com/css2?family=Courier:wght@400;700&display=swap" }
